### ISSUE TITLE
use the newer APIs for SalesOrders, Quotations, PriceLists and SalesPriceListDetails

### ISSUE THREAD

**Issue by georgeduckett** [fretje/exactonline-api-dotnet-client#11]
Per this notification, https://support.exactonline.com/community/s/knowledge-base#All-All-DNO-ReleaseNote-rn-2209-rn-appcenter-newsyncapi a few APIs are being removed and replaced with others. The model classes / services list should be updated to reflect this.

**Comment by fretje** [comment]
https://github.com/fretje/exactonline-api-dotnet-client/commit/9c8dce0812958870e20e881efa856c8cc173e8ed
