### ISSUE TITLE
Projects from other divisions are not all synchronized

### ISSUE THREAD

**Issue by StephanBis** [fretje/exactonline-api-dotnet-client#14]
Hi,

First of all, thank you for keeping the C# SDK alive!

I'm having issues with syncing projects from different divisions. Projects for the main (default) division are being synchronized without issue. However for the couple of other divisions only some projects are being synced. It will sync a couple, then skip a random number and so on. We have checked the non-syncing projects in Exact but cannot find any clue on why those particular projects are not being synced.

I'm not applying any filters, just straight up fetching all projects from all divisions. I've attached a snippet of the code I'm using.

Thank you in advance.

```
await _exactOnlineService.InitializeClient();

await _exactOnlineService.Client!.InitializeDivisionAsync(cancellationToken);

await _exactOnlineService.Database.InitializeDatabaseAsync(cancellationToken);

await _exactOnlineService.Client.SynchronizeWithAsync<SystemBase.Division>(_exactOnlineService.Database, ModelInfo.For<SystemBase.Division>().FieldNames(true), ct: cancellationToken);

var divisions = await _mediator.Send(new List.Query(), cancellationToken);

foreach (var division in divisions)
{
    await _exactOnlineService.InitializeClient(division.Id);

    await _exactOnlineService.Client.InitializeDivisionAsync(cancellationToken);

    await _exactOnlineService.Client.SynchronizeWithAsync<Project>(_exactOnlineService.Database, ModelInfo.For<Project>().FieldNames(true), ct: cancellationToken);
    await _exactOnlineService.Client.SynchronizeWithAsync<Account>(_exactOnlineService.Database, ModelInfo.For<Account>().FieldNames(true), ct: cancellationToken);
    await _exactOnlineService.Client.SynchronizeWithAsync<Item>(_exactOnlineService.Database, ModelInfo.For<Item>().FieldNames(true), ct: cancellationToken);
    await _exactOnlineService.Client.SynchronizeWithAsync<SalesItemPrice>(_exactOnlineService.Database, ModelInfo.For<SalesItemPrice>().FieldNames(true), ct: cancellationToken);	        
}
```

**Comment by fretje** [comment]
Hmm not sure... could it have something to do with permissions perhaps? Maybe the account you're using to log in doesn't have access to those divisions?

I have added logging in the latest version. You can pass an ILogger in the client constructor. If you set the minimumlevel to Debug, you should see the requests (and responses) that are executed. Maybe that can help to debug this further?

**Comment by StephanBis** [comment]
I was thinking the same thing initially, but some projects (even new ones that just got created) are syncing. I'll try debugging with the logger, thank you.

**Comment by StephanBis** [comment]
Apologies for the delayed follow-up. I've found the following filter being added to the /Projects GET call. 
`...$filter=Modified+gt+datetime'2023-11-13T19:49:18.3630000'&$select...`

Is there a reason why this  is being added by default and is there a way to disable it? 
My guess is that projects are only getting synced when they have been modified once. So new projects are not being synced until they've been actually modified, does this sound plausible?

**Comment by fretje** [comment]
This is what "synchronization" does by default. A so called "incremental" sync. It looks in the target table for the last modified datetime, and uses that to only grab the things that are updated after that date. 
It does it like this for all entities. It's a bit different for entities that support the "sync" feature (from exact online). There the "timestamp" value is used to filter instead.

If you want to do a "non incremental" or "full" sync, you have to truncate the target table first. Or at least, that's how I've implemented it in the project where I'm using this library.

**Comment by StephanBis** [comment]
I'm not quite sure why the projects didn't sync in the first place then. The specific tables were empty on initial sync. Maybe I had some kind of bug in my code when the first sync happened and that propagated in the issue I'm seeing now.
I'll have to look into how to truncate the target table while maintaining existing records that had a relation with a project and "re-attach" them afterwards.
Anways, thank you for your insights.
