### ISSUE TITLE
Project API has a Sync endpoint but ExactOnline.Client.Models.Project.Project does not inherit from SupportsSync

### ISSUE THREAD

**Issue by slabarque** [fretje/exactonline-api-dotnet-client#15]
Great work on the Sync API!

I see that there is a Sync enpoint for Projects
https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=SyncProjectProjects

But since _ExactOnline.Client.Models.Project.Project_ does not inherit from _SupportsSync_ deletes are not picked up. Although the delete endpoint does provide them. Can _ExactOnline.Client.Models.Project.Project_ be made a subclass of  _SupportsSync_ so that deletes will also get picked up?

**Comment by fretje** [comment]
Sure, I suppose it can if it's like that in the documentation...

Would you mind trying it out on a fork? And maybe create a pull request if it works?

Note: For the deletes to work you'll also have to update `ModelInfo`'s `HasDeletedEntityType` and `DeletedEntityType` properties:

https://github.com/fretje/exactonline-api-dotnet-client/blob/c03dcbadb377b3645ac9f10df131758da1fcc4ab/src/ExactOnline.Client.Sdk.Sync/ModelInfo.cs#L106-L134

**Comment by slabarque** [comment]
I'll try to take a look if I find some time
