### ISSUE TITLE
Fetching opportunity stages

### ISSUE THREAD

**Issue by StephanBis** [fretje/exactonline-api-dotnet-client#16]
Maybe I'm looking over it or it's named differently in the API, but I can't seem to find how to fetch opportunity stages. I am able to fetch opportunities themselves but not the stages they have a relation with. Do you know where I can find the stages? The Guid in the opportunity has a value, so it's definitly linked to an entity somewhere.
Thank you in advance!

**Comment by fretje** [comment]
I also don't see any api to retrieve opportunity stages at first sight...

See here for the whole list of api's: https://start.exactonline.nl/docs/HlpRestAPIResources.aspx?SourceAction=10

If you see it in there, it's possible to add support for it in this sdk... otherwise that's difficult ;-)

**Comment by Stephan-DXRS** [comment]
That's what I was afraid of, I also couldn't find any endpoint in their docs. 
I'll contact Exact support.
