### ISSUE TITLE
Authentication tokens only last 3 days

### ISSUE THREAD

**Issue by georgeduckett** [fretje/exactonline-api-dotnet-client#4]
I'm using the built in OAuth client to handle refresh tokens etc.

I'm handling the `AnyTokenUpdated` event to save the `RefreshToken`, `AccessToken` and `AccessTokenExpirationUtc`. In the constructor I pass in the saved values.

Dispite doing the above, every 3 days I'm getting the login window pop up asking for credentials. My understanding is that with the above what wouldn't happen, and certainly not that frequently.

Is there anything I'm doing wrong here, or is this a bug?

**Comment by fretje** [comment]
Sorry to get back to you so late... I didn't see any notifications for this repo...

I'm not sure what could be the problem. Are you sure the values are saved right?

I'm doing exactly what you describe (and what's also done in the example console app) in a project of mine, and there I never have to log in again. As long as you do a call before the actual refresh token is expired of course.

**Comment by georgeduckett** [comment]
Values were saved ok. Your last sentence might be the issue though. This is a console app that runs daily, so after the last call the previous day no call would be made for roughly 24 hours. My understanding is that this scenario should still work however, getting a new token automatically, but perhaps not. To get around it in the end I handled the log for getting a new token manually using the below:

```
var response = httpClient.PostAsync(_exactOnlineUrl + "/api/oauth2/token", new FormUrlEncodedContent(new Dictionary<string, string>() {
        { "refresh_token", RefreshToken },
        { "grant_type", "refresh_token" },
        { "client_id", _ClientId },
        { "client_secret", _Secret } })).Result;
                
var tst = response.Content.ReadAsStringAsync().Result;

var responseJObject = JObject.Parse(tst);

if (responseJObject.ContainsKey("access_token"))
{
    AccessToken = responseJObject.Value<string>("access_token");
    RefreshToken = responseJObject.Value<string>("refresh_token");
    AccessTokenExpirationUtc = DateTime.UtcNow.AddSeconds(responseJObject.Value<int>("expires_in"));
}
```
